### ISSUE TITLE
Timeout callback should know its request

### ISSUE THREAD

**Issue by flashhhh** [johntitus/node-horseman#124]
Hi!

Recently, I've lost 2 days of productive development to fix a bug with my horseman "scenarios". Turned out, `horseman` has its own `timeout` event which even doesn't provide any information about the failed request.

For some reason, `phantom`'s `onResourceTimeout` callback isn't working for me (`phantomjs v1.9.8`, using code `horseman.on('resourceTimeout', function(...) {...})`). So I only could use the internal callback to control my timing-outing, but when it fires, I have no idea how to get the request object (ultimately, I need a URL), which is very important info.

Need to be improved, I think. However, it would be great, if someone knows a workaround for my issue.

Thanks!

**Comment by awlayton** [comment]
Could you post example code where `.on('resourceTimeout', ...)` is not working?

**Comment by flashhhh** [comment]
[Here](http://pastebin.com/XAGjLbKp) are the sources.

I realize, that the internal timeout shouldn't be fired in my example since it's `waitFor/waitForNextPage` bounded. However, `resourceTimeout` doesn't get fired either.

Also, there is no legal way to set a timeout value for this `phantom`'s timeout, so, I guess, it's possible to have 2 different timeout handlers for mostly the same event with different values.

From my point of view, `resourceTimeout` just should work, and the internal `timeout` just shouldn't exist.

P.S.

    > node -v                                                                                                                          
    v5.5.0
    > phantomjs -v                                                                                                                     
    1.9.8
    > sw_vers -productVersion                                                                                                          
    10.11.3
    #its El-Capitan

`node-horseman` is `2.8.1`

**Comment by awlayton** [comment]
The reason for `timeout` and `resourceTimeout` is that horseman does not mess with any of the events from phantomjs, so when horseman wanted to time something out it created its own event. *I would prefer* that instead of the `timeout` event the Promise chain would just reject, but I'm big on the Promises.

The `timeout` option for horseman does not affect `resourceTimeout`, only `timeout`. There is no way to change the setting for phantom's builtin timeouts (as far as I know). Perhaps the sleep in your PHP is not long enough to timeout phantom?

**Comment by flashhhh** [comment]
@awlayton, I understand the nature of the `timeout` and all I want is to just use `resourceTimeout` of phantom without any usage of the `timeout`. However, it never gets fired. I've tried even bigger values for the `sleep`, it didn't work: page gets loaded fine without firing the `resourceTimeout`.

And, as far as I know, [there is](http://phantomjs.org/api/webpage/handler/on-resource-timeout.html) a way to change the default timeout value of the phantom.

Regarding the original problem, is there any way at least to know what resource has got failed when the internal `timeout` fires? As with `resourceTimeout`.

**Comment by awlayton** [comment]
There is no resource for a `timeout`. If `.waitForNextPage` times out waiting for a resource, a `resouceTimeout` will happen as well as the `timeout`. But that is not the *only* way that `.waitForNextPage` can timeout.

Also, thanks for the info about `settings.resourceTimeout`. I will look into that.

**Comment by awlayton** [comment]
@flashhhh you could use the `resourceRequested` and `resourceRecieved` events to make a list of pending resources, and then see what resource(s) the list contains when the `timeout` for `.waitForNextPage` occurs.

**Comment by flashhhh** [comment]
@awlayton, thanks. So I giving up trying using `resourceTimeout` until it's possible to change the timeout value.

BTW, if you can change the phantom's timeout and use `resourceTimeout` well, what's the reason to keep the internal `timeout` at all?

**Comment by awlayton** [comment]
If it were entirely up to me, it would go away and things like `.waitFor` would just reject the Promise instead of firing an event.

But if you like event type things, `timeout` is needed because not all timeouts are because of a fail request for a resource. I'll agree that every `resourceTimeout` should have a corresponding `timeout` (if `timeout` exists) since it is a kind of timeout.

Depending on how @johntitus feels, perhaps `timeout` will change/disappear in v3?

**Comment by awlayton** [comment]
Closing this as an issue, but still open to discussion of possible changes.
