### ISSUE TITLE
How to catch errors in `evaluate`?

### ISSUE THREAD

**Issue by wong2** [johntitus/node-horseman#130]
I'm trying to log errors happened in `evaluate`, but the following code doesn't work:

```
horseman
  .open('https://www.google.com')
  .evaluate(function() {
    1 / 0;
    return 1;
  })
  .then(function(value) {
    console.log(value);
  })
  .catch(function(err) {
    console.log(err);
  })
  .close()
```

**Comment by awlayton** [comment]
You would have to catch it yourself, e.g.,:
```javascript
.evaluate(function() {
    try {
        1 / 0;
        return [null, 1];
    } catch (err) {
        return [err];
    }
})
.spread(function(err, value) {
})
```

If you just want to log errors, all you have to do is connect Phantom's errors to the console:
```javascript
horseman
    .on('error', console.error)
    .open()
   /* etc. */
```
then the uncaught Error will be logged.

I *believe* this is because of how Phantom's `evaluate` works, and not because of horseman. Though it would be *possible* to re-implement part of evaluate in horseman to fix this...

**Comment by wong2** [comment]
@awlayton thanks!
