### ISSUE TITLE
Repeat a series of Steps?

### ISSUE THREAD

**Issue by LuckyLillia** [johntitus/node-horseman#140]
How do I repeat() a part of horsemanjs steps for a number of times?

For example, I login to a website once. Then, I repeat a series of steps, like tweeting a couple of blog posts.

Can I do this?

Example:

```javascript
for(var count=1;count<=2;count++) {

 .open("google.com")
  .type("input[name='q']","Get search terms from array")
  .click("button:contains('Google Search')")
  .wait(5000)

// Do something from nodejs with the search results?

 }
```

**Comment by johntitus** [comment]
It's a bit tricky, because each of the `horseman` calls is asynchronous, while a `for` loop is sync.  You have to have horseman return a promise, and then take action based on the result.

Take a look at this example:

https://github.com/johntitus/node-horseman/blob/master/examples/links.js

The `scrape` function is called repeatedly if there is a next page.  Esentially, `scrape` returns a promise, which may return another promise, etc.

**Comment by awlayton** [comment]
What you posted is not valid JavaScript. You have to have an actual variable you are using the `.` operator on.

```javascript

var chain = horseman; // You cannot chain off nothing

for(var count=1;count<=2;count++) {

 chain = chain.open("google.com")
  .type("input[name='q']","Get search terms from array")
  .click("button:contains('Google Search')")
  .wait(5000)

// Do something from nodejs with the search results?

 }
```

Horseman is Promised based, you should learn about Promises before opening issues like this. Your question was a Promise chaining question and ***not*** a horseman question.

**Comment by kyuchukovv** [comment]
The links.js which @johntitus posted is not working.
