### ISSUE TITLE
Can we get phantomjs object from horseman object and call it without any process

### ISSUE THREAD

**Issue by sbsomya** [johntitus/node-horseman#177]
Hi

Want to get the base64 string as 

`var base64str = page.renderBase64("PNG");`

Without calling .then function

**Comment by awlayton** [comment]
Short answer: you can't.

You can get the node-phantom-simple object like so:
```javascript
var horseman = new Horseman();

var page = horseman.page;
```

**However**, you would still have to do this:
```javascript
page.renderBase64('PNG', function(err, base64str) {
    // Do stuff
});
```

You *cannot* do thing like you do directly in PhantomJS, because it runs in a *separate* process from Node.js. All the communication between the PhantomJS process and the Node.js is *asynchronous*.
