### ISSUE TITLE
Empty 'networkRequest' object for 'onResourceRequested' event

### ISSUE THREAD

**Issue by VDenisyuk** [johntitus/node-horseman#264]
Hi all!
Today I faced with strange issue with empty networkRequest object for onResourceRequested.
I tried to handle resource request like this

```javascript
horseman
  .userAgent('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0')
  .on('resourceRequested', function(reqData, req){
    if (reqData.url.indexOf('someText') > -1) {
      req.abort();
    } 
  })
```
but it gives an error. 
There is no method abort() for _req_ object. Actually, there are no methods at all inside this object.

**Comment by awlayton** [comment]
This is a known condition. I choose not to call it an issue because it is not a bug, but a consequence of the async nature of the connection between Node.JS and PhantomJS. When your handler gets run, the request is actually already over (see baudehlo/node-phantom-simple#98).

Try using Horseman's [`.at()`](https://github.com/johntitus/node-horseman#atevent-callback) rather than `.on()` to register a function to run at the time of the event. Keep in mind that with `.at()` the function runs in the PhantomJS environment and not in Node.JS.
