### ISSUE TITLE
Run horseman in asynchronous way with callback 

### ISSUE THREAD

**Issue by thanhthang20** [johntitus/node-horseman#34]
Is there any way to run horseman in asynchronous way with callback. In below example, I have to wait horseman for finishing to run 'myFunction'. Is there any way to run 'myFunction' without waiting for horseman?

```
var Horseman = require('node-horseman');
var horseman = new Horseman();

var numLinks = horseman
  .userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0")
  .open('http://www.google.com')
  .type('input[name="q"]', 'github')
  .click("button:contains('Google Search')")
  .waitForNextPage()
  .count("li.g");

console.log("Number of links: " + numLinks);
horseman.close();

// call myFuction()
```

**Comment by johntitus** [comment]
Not quite sure I follow. You can't do two things at the same time with horseman as it blocks execution while it runs.  However, you can do this:

```js
var Horseman = require('node-horseman');
var horseman = new Horseman();

var numLinks = horseman
  .userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0")
  .open('http://www.google.com');

// call myFuction()
horseman
  .type('input[name="q"]', 'github')
  .click("button:contains('Google Search')")
  .waitForNextPage()
  .count("li.g");

console.log("Number of links: " + numLinks);
horseman.close();
```

**Comment by thanhthang20** [comment]
Horseman blocks execution, so we can not run multi horseman instances at the same time, right?. Is there any way to run multi horseman instances?

**Comment by johntitus** [comment]
You could run horseman in child processes. That way when horseman blocks, only that process will be blocked.

https://nodejs.org/api/child_process.html

**Comment by greim** [comment]
I agree with @thanhthang20. Blocking the thread is bad in node because there's only one thread. It would be nice if there was a way to do this asynchronously, for example with promises. Then you could use `then()` chaining, or better yet, [generators](https://www.npmjs.com/package/co) or even [async functions](https://github.com/lukehoban/ecmascript-asyncawait). A node lib that blocks the thread is basically unusable.

With promises and async functions for example it could look like this:

```js
var Horseman = require('node-horseman');

async function run() {
  var horseman = new Horseman();
  await horseman.userAgent("Mozilla/5.0 ...")
  await horseman.open('http://www.google.com');
  await horseman.type('input[name="q"]', 'github');
  await horseman.click("button:contains('Google Search')");
  await horseman.waitForNextPage()
  var numLinks = await horseman.count("li.g");
  console.log("Number of links: " + numLinks);
  horseman.close();
}

run();
```

**Comment by flashhhh** [comment]
Agree to the above. Didn't pick your lib only because of this.

**Comment by bchr02** [comment]
Also agree. Horseman should automatically make sure not to block the thread. We shouldn't have to create child processes.

**Comment by johntitus** [comment]
It was a design decision to block, to make the API easier to use. There are many async phantomjs runners. You may want to check out:

https://github.com/segmentio/nightmare

I've been looking at generators & such, but it's a ton of work to move to that.

**Comment by flashhhh** [comment]
> I've been looking at generators & such, but it's a ton of work to move to that.

Actually, no. All you need is to implement a promise based interface so generators could work with it via libs like https://github.com/jmar777/suspend.

And, after a few years, people would use it via ES7 like @greim described.

I like your lib, good job, but sync libraries are really unusable in node environment. You can only write tests with them.

And people use `child_process`, basically, only because of performance purposes. Nobody would use it just because he needs to run sync task asynchronously.

**Comment by johntitus** [comment]
Linking to #40 for comments
